#pragma once
/*
*      Copyright (C) 2005-2015 Team XBMC
*      http://xbmc.org
*
*  This Program is free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2, or (at your option)
*  any later version.
*
*  This Program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
*  GNU General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with XBMC; see the file COPYING.  If not, see
*  <http://www.gnu.org/licenses/>.
*
*/

// conditions for window retrieval
#define WINDOW_CONDITION_HAS_LIST_ITEMS  1
#define WINDOW_CONDITION_IS_MEDIA_WINDOW 2

//leave the lower 10 bits to labels, should give us ~1024
//labels per category
#define CATEGORY_MASK 0xFFFFFC00
#define PLAYER_MASK (1<<10)
#define WEATHER_MASK    (1<<11)
#define SYSTEM_MASK     (1<<12)
#define NETWORK_MASK        (1<<13)
#define PVR_MASK            (1<<14)
#define MUSICPLAYER_MASK    (1<<15)
#define VIDEOPLAYER_MASK    (1<<16)
#define MUSICPM_MASK        (1<<17)
#define PLAYLIST_MASK       (1<<18)
#define VISUALISATION_MASK  (1<<19)

#define PLAYER_HAS_MEDIA             PLAYER_MASK +  1
#define PLAYER_HAS_AUDIO             PLAYER_MASK +  2
#define PLAYER_HAS_VIDEO             PLAYER_MASK +  3
#define PLAYER_PLAYING               PLAYER_MASK +  4
#define PLAYER_PAUSED                PLAYER_MASK +  5
#define PLAYER_REWINDING             PLAYER_MASK +  6
#define PLAYER_REWINDING_2x          PLAYER_MASK +  7
#define PLAYER_REWINDING_4x          PLAYER_MASK +  8
#define PLAYER_REWINDING_8x          PLAYER_MASK +  9
#define PLAYER_REWINDING_16x         PLAYER_MASK + 10
#define PLAYER_REWINDING_32x         PLAYER_MASK + 11
#define PLAYER_FORWARDING            PLAYER_MASK + 12
#define PLAYER_FORWARDING_2x         PLAYER_MASK + 13
#define PLAYER_FORWARDING_4x         PLAYER_MASK + 14
#define PLAYER_FORWARDING_8x         PLAYER_MASK + 15
#define PLAYER_FORWARDING_16x        PLAYER_MASK + 16
#define PLAYER_FORWARDING_32x        PLAYER_MASK + 17
#define PLAYER_CAN_RECORD            PLAYER_MASK + 18
#define PLAYER_RECORDING             PLAYER_MASK + 19
#define PLAYER_CACHING               PLAYER_MASK + 20
#define PLAYER_DISPLAY_AFTER_SEEK    PLAYER_MASK + 21
#define PLAYER_PROGRESS              PLAYER_MASK + 22
#define PLAYER_SEEKBAR               PLAYER_MASK + 23
#define PLAYER_SEEKTIME              PLAYER_MASK + 24
#define PLAYER_SEEKING               PLAYER_MASK + 25
#define PLAYER_SHOWTIME              PLAYER_MASK + 26
#define PLAYER_TIME                  PLAYER_MASK + 27
#define PLAYER_TIME_REMAINING        PLAYER_MASK + 28
#define PLAYER_DURATION              PLAYER_MASK + 29
#define PLAYER_SHOWCODEC             PLAYER_MASK + 30
#define PLAYER_SHOWINFO              PLAYER_MASK + 31
#define PLAYER_VOLUME                PLAYER_MASK + 32
#define PLAYER_MUTED                 PLAYER_MASK + 33
#define PLAYER_HASDURATION           PLAYER_MASK + 34
#define PLAYER_CHAPTER               PLAYER_MASK + 35
#define PLAYER_CHAPTERCOUNT          PLAYER_MASK + 36
#define PLAYER_TIME_SPEED            PLAYER_MASK + 37
#define PLAYER_FINISH_TIME           PLAYER_MASK + 38
#define PLAYER_CACHELEVEL            PLAYER_MASK + 39
#define PLAYER_STAR_RATING           PLAYER_MASK + 40
#define PLAYER_CHAPTERNAME           PLAYER_MASK + 41
#define PLAYER_SUBTITLE_DELAY        PLAYER_MASK + 42
#define PLAYER_AUDIO_DELAY           PLAYER_MASK + 43
#define PLAYER_PASSTHROUGH           PLAYER_MASK + 44
#define PLAYER_PATH                  PLAYER_MASK + 45
#define PLAYER_FILEPATH              PLAYER_MASK + 46
#define PLAYER_SEEKOFFSET            PLAYER_MASK + 47
#define PLAYER_PROGRESS_CACHE        PLAYER_MASK + 48
#define PLAYER_ITEM_ART              PLAYER_MASK + 49
#define PLAYER_CAN_PAUSE             PLAYER_MASK + 50
#define PLAYER_CAN_SEEK              PLAYER_MASK + 51
#define PLAYER_START_TIME            PLAYER_MASK + 52
#define PLAYER_TITLE                 PLAYER_MASK + 53
#define PLAYER_ISINTERNETSTREAM      PLAYER_MASK + 54
#define PLAYER_FILENAME              PLAYER_MASK + 55
#define PLAYER_SEEKSTEPSIZE          PLAYER_MASK + 56

#define WEATHER_CONDITIONS         WEATHER_MASK + 0
#define WEATHER_TEMPERATURE        WEATHER_MASK + 1
#define WEATHER_LOCATION           WEATHER_MASK + 2
#define WEATHER_IS_FETCHED         WEATHER_MASK + 3
#define WEATHER_FANART_CODE        WEATHER_MASK + 4
#define WEATHER_PLUGIN             WEATHER_MASK + 5

#define SYSTEM_TEMPERATURE_UNITS    SYSTEM_MASK +  6
#define SYSTEM_PROGRESS_BAR         SYSTEM_MASK +  7
#define SYSTEM_LANGUAGE             SYSTEM_MASK +  8
#define SYSTEM_TIME                 SYSTEM_MASK + 10
#define SYSTEM_DATE                 SYSTEM_MASK + 11
#define SYSTEM_CPU_TEMPERATURE      SYSTEM_MASK + 12
#define SYSTEM_GPU_TEMPERATURE      SYSTEM_MASK + 13
#define SYSTEM_FAN_SPEED            SYSTEM_MASK + 14
#define SYSTEM_FREE_SPACE_C         SYSTEM_MASK + 15
// #define SYSTEM_FREE_SPACE_D      SYSTEM_MASK +   116 //116 is reserved for space on D
#define SYSTEM_FREE_SPACE_E         SYSTEM_MASK + 17
#define SYSTEM_FREE_SPACE_F         SYSTEM_MASK + 18
#define SYSTEM_FREE_SPACE_G         SYSTEM_MASK + 19
#define SYSTEM_BUILD_VERSION        SYSTEM_MASK + 20
#define SYSTEM_BUILD_DATE           SYSTEM_MASK + 21
#define SYSTEM_ETHERNET_LINK_ACTIVE SYSTEM_MASK + 22
#define SYSTEM_FPS                  SYSTEM_MASK + 23
#define SYSTEM_ALWAYS_TRUE          SYSTEM_MASK + 25   // useful for <visible fade="10" start="hidden">true</visible>, to fade in a control
#define SYSTEM_ALWAYS_FALSE         SYSTEM_MASK + 26   // used for <visible fade="10">false</visible>, to fade out a control (ie not particularly useful!)
#define SYSTEM_MEDIA_DVD            SYSTEM_MASK + 27
#define SYSTEM_DVDREADY             SYSTEM_MASK + 28
#define SYSTEM_HAS_ALARM            SYSTEM_MASK + 29
#define SYSTEM_SCREEN_MODE          SYSTEM_MASK + 32
#define SYSTEM_SCREEN_WIDTH         SYSTEM_MASK + 33
#define SYSTEM_SCREEN_HEIGHT        SYSTEM_MASK + 34
#define SYSTEM_CURRENT_WINDOW       SYSTEM_MASK + 35
#define SYSTEM_CURRENT_CONTROL      SYSTEM_MASK + 36
#define SYSTEM_DVD_LABEL            SYSTEM_MASK + 38
#define SYSTEM_HASLOCKS             SYSTEM_MASK + 40
#define SYSTEM_ISMASTER             SYSTEM_MASK + 41
#define SYSTEM_TRAYOPEN             SYSTEM_MASK + 42
#define SYSTEM_SHOW_EXIT_BUTTON     SYSTEM_MASK + 43
#define SYSTEM_ALARM_POS            SYSTEM_MASK + 44
#define SYSTEM_LOGGEDON             SYSTEM_MASK + 45
#define SYSTEM_PROFILENAME          SYSTEM_MASK + 46
#define SYSTEM_PROFILETHUMB         SYSTEM_MASK + 47
#define SYSTEM_HAS_LOGINSCREEN      SYSTEM_MASK + 48
#define SYSTEM_HDD_SMART            SYSTEM_MASK + 50
#define SYSTEM_HDD_TEMPERATURE      SYSTEM_MASK + 51
#define SYSTEM_HDD_MODEL            SYSTEM_MASK + 52
#define SYSTEM_HDD_SERIAL           SYSTEM_MASK + 53
#define SYSTEM_HDD_FIRMWARE         SYSTEM_MASK + 54
#define SYSTEM_HDD_PASSWORD         SYSTEM_MASK + 56
#define SYSTEM_HDD_LOCKSTATE        SYSTEM_MASK + 57
#define SYSTEM_HDD_LOCKKEY          SYSTEM_MASK + 58
#define SYSTEM_INTERNET_STATE       SYSTEM_MASK + 59
#define SYSTEM_ALARM_LESS_OR_EQUAL  SYSTEM_MASK + 80
#define SYSTEM_PROFILECOUNT         SYSTEM_MASK + 81
#define SYSTEM_ISFULLSCREEN         SYSTEM_MASK + 82
#define SYSTEM_ISSTANDALONE         SYSTEM_MASK + 83
#define SYSTEM_ISINHIBIT            SYSTEM_MASK + 84
#define SYSTEM_HAS_SHUTDOWN         SYSTEM_MASK + 85
#define SYSTEM_HAS_PVR              SYSTEM_MASK + 86
#define SYSTEM_STARTUP_WINDOW       SYSTEM_MASK + 87
#define SYSTEM_STEREOSCOPIC_MODE    SYSTEM_MASK + 88
#define SYSTEM_BUILD_VERSION_SHORT  SYSTEM_MASK + 89

#define NETWORK_IP_ADDRESS          NETWORK_MASK + 0
#define NETWORK_MAC_ADDRESS         NETWORK_MASK + 1
#define NETWORK_IS_DHCP             NETWORK_MASK + 2
#define NETWORK_LINK_STATE          NETWORK_MASK + 3
#define NETWORK_SUBNET_MASK         NETWORK_MASK + 4
#define NETWORK_GATEWAY_ADDRESS     NETWORK_MASK + 5
#define NETWORK_DNS1_ADDRESS        NETWORK_MASK + 6
#define NETWORK_DNS2_ADDRESS        NETWORK_MASK + 7
#define NETWORK_DHCP_ADDRESS        NETWORK_MASK + 8

#define MUSICPLAYER_TITLE               MUSICPLAYER_MASK + 0
#define MUSICPLAYER_ALBUM               MUSICPLAYER_MASK + 1
#define MUSICPLAYER_ARTIST              MUSICPLAYER_MASK + 2
#define MUSICPLAYER_GENRE               MUSICPLAYER_MASK + 3
#define MUSICPLAYER_YEAR                MUSICPLAYER_MASK + 4
#define MUSICPLAYER_DURATION            MUSICPLAYER_MASK + 5
#define MUSICPLAYER_TRACK_NUMBER        MUSICPLAYER_MASK + 8
#define MUSICPLAYER_COVER               MUSICPLAYER_MASK + 10
#define MUSICPLAYER_BITRATE             MUSICPLAYER_MASK + 11
#define MUSICPLAYER_PLAYLISTLEN         MUSICPLAYER_MASK + 12
#define MUSICPLAYER_PLAYLISTPOS         MUSICPLAYER_MASK + 13
#define MUSICPLAYER_CHANNELS            MUSICPLAYER_MASK + 14
#define MUSICPLAYER_BITSPERSAMPLE       MUSICPLAYER_MASK + 15
#define MUSICPLAYER_SAMPLERATE          MUSICPLAYER_MASK + 16
#define MUSICPLAYER_CODEC               MUSICPLAYER_MASK + 17
#define MUSICPLAYER_DISC_NUMBER         MUSICPLAYER_MASK + 18
#define MUSICPLAYER_RATING              MUSICPLAYER_MASK + 19
#define MUSICPLAYER_COMMENT             MUSICPLAYER_MASK + 20
#define MUSICPLAYER_LYRICS              MUSICPLAYER_MASK + 21
#define MUSICPLAYER_HASPREVIOUS         MUSICPLAYER_MASK + 22
#define MUSICPLAYER_HASNEXT             MUSICPLAYER_MASK + 23
#define MUSICPLAYER_EXISTS              MUSICPLAYER_MASK + 24
#define MUSICPLAYER_PLAYLISTPLAYING     MUSICPLAYER_MASK + 25
#define MUSICPLAYER_ALBUM_ARTIST        MUSICPLAYER_MASK + 26
#define MUSICPLAYER_PLAYCOUNT           MUSICPLAYER_MASK + 27
#define MUSICPLAYER_LASTPLAYED          MUSICPLAYER_MASK + 28
#define MUSICPLAYER_CHANNEL_NAME        MUSICPLAYER_MASK + 29
#define MUSICPLAYER_CHANNEL_NUMBER      MUSICPLAYER_MASK + 30
#define MUSICPLAYER_CHANNEL_GROUP       MUSICPLAYER_MASK + 31
#define MUSICPLAYER_SUB_CHANNEL_NUMBER  MUSICPLAYER_MASK + 32
#define MUSICPLAYER_CHANNEL_NUMBER_LBL  MUSICPLAYER_MASK + 33
#define MUSICPLAYER_CONTENT             MUSICPLAYER_MASK + 34

#define VIDEOPLAYER_TITLE               VIDEOPLAYER_MASK + 1 
#define VIDEOPLAYER_GENRE               VIDEOPLAYER_MASK + 2 
#define VIDEOPLAYER_DIRECTOR            VIDEOPLAYER_MASK + 3 
#define VIDEOPLAYER_YEAR                VIDEOPLAYER_MASK + 4 
#define VIDEOPLAYER_HASSUBTITLES        VIDEOPLAYER_MASK + 5 
#define VIDEOPLAYER_SUBTITLESENABLED    VIDEOPLAYER_MASK + 6 
#define VIDEOPLAYER_COVER               VIDEOPLAYER_MASK + 7 
#define VIDEOPLAYER_USING_OVERLAYS      VIDEOPLAYER_MASK + 8 
#define VIDEOPLAYER_ISFULLSCREEN        VIDEOPLAYER_MASK + 9 
#define VIDEOPLAYER_HASMENU             VIDEOPLAYER_MASK + 10
#define VIDEOPLAYER_PLAYLISTLEN         VIDEOPLAYER_MASK + 11
#define VIDEOPLAYER_PLAYLISTPOS         VIDEOPLAYER_MASK + 12
#define VIDEOPLAYER_EVENT               VIDEOPLAYER_MASK + 13
#define VIDEOPLAYER_ORIGINALTITLE       VIDEOPLAYER_MASK + 14
#define VIDEOPLAYER_PLOT                VIDEOPLAYER_MASK + 15
#define VIDEOPLAYER_PLOT_OUTLINE        VIDEOPLAYER_MASK + 16
#define VIDEOPLAYER_EPISODE             VIDEOPLAYER_MASK + 17
#define VIDEOPLAYER_SEASON              VIDEOPLAYER_MASK + 18
#define VIDEOPLAYER_RATING              VIDEOPLAYER_MASK + 19
#define VIDEOPLAYER_TVSHOW              VIDEOPLAYER_MASK + 20
#define VIDEOPLAYER_PREMIERED           VIDEOPLAYER_MASK + 21
#define VIDEOPLAYER_CONTENT             VIDEOPLAYER_MASK + 22
#define VIDEOPLAYER_STUDIO              VIDEOPLAYER_MASK + 23
#define VIDEOPLAYER_MPAA                VIDEOPLAYER_MASK + 24
#define VIDEOPLAYER_CAST                VIDEOPLAYER_MASK + 25
#define VIDEOPLAYER_CAST_AND_ROLE       VIDEOPLAYER_MASK + 26
#define VIDEOPLAYER_ARTIST              VIDEOPLAYER_MASK + 27
#define VIDEOPLAYER_ALBUM               VIDEOPLAYER_MASK + 28
#define VIDEOPLAYER_WRITER              VIDEOPLAYER_MASK + 29
#define VIDEOPLAYER_TAGLINE             VIDEOPLAYER_MASK + 30
#define VIDEOPLAYER_HAS_INFO            VIDEOPLAYER_MASK + 31
#define VIDEOPLAYER_TOP250              VIDEOPLAYER_MASK + 32
#define VIDEOPLAYER_RATING_AND_VOTES    VIDEOPLAYER_MASK + 33
#define VIDEOPLAYER_TRAILER             VIDEOPLAYER_MASK + 34
#define VIDEOPLAYER_VIDEO_CODEC         VIDEOPLAYER_MASK + 35
#define VIDEOPLAYER_VIDEO_RESOLUTION    VIDEOPLAYER_MASK + 36
#define VIDEOPLAYER_AUDIO_CODEC         VIDEOPLAYER_MASK + 37
#define VIDEOPLAYER_AUDIO_CHANNELS      VIDEOPLAYER_MASK + 38
#define VIDEOPLAYER_VIDEO_ASPECT        VIDEOPLAYER_MASK + 39
#define VIDEOPLAYER_HASTELETEXT         VIDEOPLAYER_MASK + 40
#define VIDEOPLAYER_COUNTRY             VIDEOPLAYER_MASK + 41
#define VIDEOPLAYER_PLAYCOUNT           VIDEOPLAYER_MASK + 42
#define VIDEOPLAYER_LASTPLAYED          VIDEOPLAYER_MASK + 43
#define VIDEOPLAYER_STARTTIME           VIDEOPLAYER_MASK + 44
#define VIDEOPLAYER_ENDTIME             VIDEOPLAYER_MASK + 45
#define VIDEOPLAYER_NEXT_TITLE          VIDEOPLAYER_MASK + 46
#define VIDEOPLAYER_NEXT_GENRE          VIDEOPLAYER_MASK + 47
#define VIDEOPLAYER_NEXT_PLOT           VIDEOPLAYER_MASK + 48
#define VIDEOPLAYER_NEXT_PLOT_OUTLINE   VIDEOPLAYER_MASK + 49
#define VIDEOPLAYER_NEXT_STARTTIME      VIDEOPLAYER_MASK + 50
#define VIDEOPLAYER_NEXT_ENDTIME        VIDEOPLAYER_MASK + 51
#define VIDEOPLAYER_NEXT_DURATION       VIDEOPLAYER_MASK + 52
#define VIDEOPLAYER_CHANNEL_NAME        VIDEOPLAYER_MASK + 53
#define VIDEOPLAYER_CHANNEL_NUMBER      VIDEOPLAYER_MASK + 54
#define VIDEOPLAYER_CHANNEL_GROUP       VIDEOPLAYER_MASK + 55
#define VIDEOPLAYER_PARENTAL_RATING     VIDEOPLAYER_MASK + 56
#define VIDEOPLAYER_HAS_EPG             VIDEOPLAYER_MASK + 57
#define VIDEOPLAYER_VOTES               VIDEOPLAYER_MASK + 58
#define VIDEOPLAYER_IS_STEREOSCOPIC     VIDEOPLAYER_MASK + 59
#define VIDEOPLAYER_STEREOSCOPIC_MODE   VIDEOPLAYER_MASK + 60
#define VIDEOPLAYER_SUBTITLES_LANG      VIDEOPLAYER_MASK + 61
#define VIDEOPLAYER_AUDIO_LANG          VIDEOPLAYER_MASK + 62
#define VIDEOPLAYER_SUB_CHANNEL_NUMBER  VIDEOPLAYER_MASK + 63
#define VIDEOPLAYER_CHANNEL_NUMBER_LBL  VIDEOPLAYER_MASK + 64
#define VIDEOPLAYER_CAN_RESUME_LIVE_TV  VIDEOPLAYER_MASK + 65
#define VIDEOPLAYER_IMDBNUMBER          VIDEOPLAYER_MASK + 66
#define VIDEOPLAYER_EPISODENAME         VIDEOPLAYER_MASK + 67

#define CONTAINER_HAS_PARENT_ITEM    341
#define CONTAINER_CAN_FILTER         342
#define CONTAINER_CAN_FILTERADVANCED 343
#define CONTAINER_FILTERED           344

#define CONTAINER_SCROLL_PREVIOUS   345 // NOTE: These 5 must be kept in this consecutive order
#define CONTAINER_MOVE_PREVIOUS     346
#define CONTAINER_STATIC            347
#define CONTAINER_MOVE_NEXT         348
#define CONTAINER_SCROLL_NEXT       349
#define CONTAINER_ISUPDATING        350
#define CONTAINER_HASFILES          351
#define CONTAINER_HASFOLDERS        352
#define CONTAINER_STACKED           353
#define CONTAINER_FOLDERNAME        354
#define CONTAINER_SCROLLING         355
#define CONTAINER_PLUGINNAME        356
#define CONTAINER_PROPERTY          357
#define CONTAINER_SORT_DIRECTION    358
#define CONTAINER_NUM_ITEMS         359
#define CONTAINER_FOLDERPATH        360
#define CONTAINER_CONTENT           361
#define CONTAINER_HAS_THUMB         362
#define CONTAINER_SORT_METHOD       363
#define CONTAINER_CURRENT_ITEM      364
#define CONTAINER_ART               365
#define CONTAINER_HAS_FOCUS         366
#define CONTAINER_ROW               367
#define CONTAINER_COLUMN            368
#define CONTAINER_POSITION          369
#define CONTAINER_VIEWMODE          370
#define CONTAINER_HAS_NEXT          371
#define CONTAINER_HAS_PREVIOUS      372
#define CONTAINER_SUBITEM           373
#define CONTAINER_NUM_PAGES         374
#define CONTAINER_CURRENT_PAGE      375
#define CONTAINER_SHOWPLOT          376
#define CONTAINER_TOTALTIME         377
#define CONTAINER_SORT_ORDER        378
#define CONTAINER_TOTALWATCHED      379
#define CONTAINER_TOTALUNWATCHED    380

#define MUSICPM_ENABLED             MUSICPM_MASK + 1
#define MUSICPM_SONGSPLAYED         MUSICPM_MASK + 2
#define MUSICPM_MATCHINGSONGS       MUSICPM_MASK + 3
#define MUSICPM_MATCHINGSONGSPICKED MUSICPM_MASK + 4
#define MUSICPM_MATCHINGSONGSLEFT   MUSICPM_MASK + 5
#define MUSICPM_RELAXEDSONGSPICKED  MUSICPM_MASK + 6
#define MUSICPM_RANDOMSONGSPICKED   MUSICPM_MASK + 7

#define PLAYLIST_LENGTH             PLAYLIST_MASK + 0
#define PLAYLIST_POSITION           PLAYLIST_MASK + 1
#define PLAYLIST_RANDOM             PLAYLIST_MASK + 2
#define PLAYLIST_REPEAT             PLAYLIST_MASK + 3
#define PLAYLIST_ISRANDOM           PLAYLIST_MASK + 4
#define PLAYLIST_ISREPEAT           PLAYLIST_MASK + 5
#define PLAYLIST_ISREPEATONE        PLAYLIST_MASK + 6

#define VISUALISATION_LOCKED        VISUALISATION_MASK + 0
#define VISUALISATION_PRESET        VISUALISATION_MASK + 1
#define VISUALISATION_NAME          VISUALISATION_MASK + 2
#define VISUALISATION_ENABLED       VISUALISATION_MASK + 3

#define STRING_IS_EMPTY             410
#define STRING_COMPARE              411
#define STRING_STR                  412
#define INTEGER_GREATER_THAN        413
#define STRING_STR_LEFT             414
#define STRING_STR_RIGHT            415

#define SKIN_BOOL                   600
#define SKIN_STRING                 601
#define SKIN_THEME                  604
#define SKIN_COLOUR_THEME           605
#define SKIN_HAS_THEME              606
#define SKIN_ASPECT_RATIO           607



#define LIBRARY_HAS_MUSIC           720
#define LIBRARY_HAS_VIDEO           721
#define LIBRARY_HAS_MOVIES          722
#define LIBRARY_HAS_MOVIE_SETS      723
#define LIBRARY_HAS_TVSHOWS         724
#define LIBRARY_HAS_MUSICVIDEOS     725
#define LIBRARY_HAS_SINGLES         726
#define LIBRARY_HAS_COMPILATIONS    727
#define LIBRARY_IS_SCANNING         728
#define LIBRARY_IS_SCANNING_VIDEO   729
#define LIBRARY_IS_SCANNING_MUSIC   730



#define SLIDESHOW_ISPAUSED          800
#define SLIDESHOW_ISRANDOM          801
#define SLIDESHOW_ISACTIVE          802
#define SLIDESHOW_ISVIDEO           803

#define SLIDE_INFO_START            900
#define SLIDE_INFO_END              980

#define FANART_COLOR1               1000
#define FANART_COLOR2               1001
#define FANART_COLOR3               1002
#define FANART_IMAGE                1003

#define SYSTEM_PROFILEAUTOLOGIN     1004

#define PVR_CONDITIONS_START        1100
#define PVR_IS_RECORDING            (PVR_CONDITIONS_START)
#define PVR_HAS_TIMER               (PVR_CONDITIONS_START + 1)
#define PVR_HAS_NONRECORDING_TIMER  (PVR_CONDITIONS_START + 2)
#define PVR_HAS_EPG                 (PVR_CONDITIONS_START + 3)
#define PVR_HAS_TXT                 (PVR_CONDITIONS_START + 4)
#define PVR_HAS_DIRECTOR            (PVR_CONDITIONS_START + 5)
#define PVR_IS_PLAYING_TV           (PVR_CONDITIONS_START + 6)
#define PVR_IS_PLAYING_RADIO        (PVR_CONDITIONS_START + 7)
#define PVR_IS_PLAYING_RECORDING    (PVR_CONDITIONS_START + 8)
#define PVR_ACTUAL_STREAM_ENCRYPTED (PVR_CONDITIONS_START + 9)
#define PVR_HAS_TV_CHANNELS         (PVR_CONDITIONS_START + 10)
#define PVR_HAS_RADIO_CHANNELS      (PVR_CONDITIONS_START + 11)
#define PVR_CONDITIONS_END          PVR_HAS_RADIO_CHANNELS

#define PVR_STRINGS_START           1200
#define PVR_NEXT_RECORDING_CHANNEL  (PVR_STRINGS_START)
#define PVR_NEXT_RECORDING_CHAN_ICO (PVR_STRINGS_START + 1)
#define PVR_NEXT_RECORDING_DATETIME (PVR_STRINGS_START + 2)
#define PVR_NEXT_RECORDING_TITLE    (PVR_STRINGS_START + 3)
#define PVR_NOW_RECORDING_CHANNEL   (PVR_STRINGS_START + 4)
#define PVR_NOW_RECORDING_CHAN_ICO  (PVR_STRINGS_START + 5)
#define PVR_NOW_RECORDING_DATETIME  (PVR_STRINGS_START + 6)
#define PVR_NOW_RECORDING_TITLE     (PVR_STRINGS_START + 7)
#define PVR_BACKEND_NAME            (PVR_STRINGS_START + 8)
#define PVR_BACKEND_VERSION         (PVR_STRINGS_START + 9)
#define PVR_BACKEND_HOST            (PVR_STRINGS_START + 10)
#define PVR_BACKEND_DISKSPACE       (PVR_STRINGS_START + 11)
#define PVR_BACKEND_CHANNELS        (PVR_STRINGS_START + 12)
#define PVR_BACKEND_TIMERS          (PVR_STRINGS_START + 13)
#define PVR_BACKEND_RECORDINGS      (PVR_STRINGS_START + 14)
#define PVR_BACKEND_DELETED_RECORDINGS (PVR_STRINGS_START + 15)
#define PVR_BACKEND_NUMBER          (PVR_STRINGS_START + 16)
#define PVR_TOTAL_DISKSPACE         (PVR_STRINGS_START + 17)
#define PVR_NEXT_TIMER              (PVR_STRINGS_START + 18)
#define PVR_PLAYING_DURATION        (PVR_STRINGS_START + 19)
#define PVR_PLAYING_TIME            (PVR_STRINGS_START + 20)
#define PVR_PLAYING_PROGRESS        (PVR_STRINGS_START + 21)
#define PVR_ACTUAL_STREAM_CLIENT    (PVR_STRINGS_START + 22)
#define PVR_ACTUAL_STREAM_DEVICE    (PVR_STRINGS_START + 23)
#define PVR_ACTUAL_STREAM_STATUS    (PVR_STRINGS_START + 24)
#define PVR_ACTUAL_STREAM_SIG       (PVR_STRINGS_START + 25)
#define PVR_ACTUAL_STREAM_SNR       (PVR_STRINGS_START + 26)
#define PVR_ACTUAL_STREAM_SIG_PROGR (PVR_STRINGS_START + 27)
#define PVR_ACTUAL_STREAM_SNR_PROGR (PVR_STRINGS_START + 28)
#define PVR_ACTUAL_STREAM_BER       (PVR_STRINGS_START + 29)
#define PVR_ACTUAL_STREAM_UNC       (PVR_STRINGS_START + 30)
#define PVR_ACTUAL_STREAM_VIDEO_BR  (PVR_STRINGS_START + 31)
#define PVR_ACTUAL_STREAM_AUDIO_BR  (PVR_STRINGS_START + 32)
#define PVR_ACTUAL_STREAM_DOLBY_BR  (PVR_STRINGS_START + 33)
#define PVR_ACTUAL_STREAM_CRYPTION  (PVR_STRINGS_START + 34)
#define PVR_ACTUAL_STREAM_SERVICE   (PVR_STRINGS_START + 35)
#define PVR_ACTUAL_STREAM_MUX       (PVR_STRINGS_START + 36)
#define PVR_ACTUAL_STREAM_PROVIDER  (PVR_STRINGS_START + 37)
#define PVR_BACKEND_DISKSPACE_PROGR (PVR_STRINGS_START + 38)
#define PVR_TIMESHIFT_START_TIME    (PVR_STRINGS_START + 39)
#define PVR_TIMESHIFT_END_TIME      (PVR_STRINGS_START + 40)
#define PVR_TIMESHIFT_PLAY_TIME     (PVR_STRINGS_START + 41)
#define PVR_TIMESHIFT_PROGRESS      (PVR_STRINGS_START + 42)
#define PVR_STRINGS_END             PVR_TIMESHIFT_PROGRESS

#define ADSP_CONDITIONS_START       1300
#define ADSP_IS_ACTIVE              (ADSP_CONDITIONS_START)
#define ADSP_HAS_INPUT_RESAMPLE     (ADSP_CONDITIONS_START + 1)
#define ADSP_HAS_PRE_PROCESS        (ADSP_CONDITIONS_START + 2)
#define ADSP_HAS_MASTER_PROCESS     (ADSP_CONDITIONS_START + 3)
#define ADSP_HAS_POST_PROCESS       (ADSP_CONDITIONS_START + 4)
#define ADSP_HAS_OUTPUT_RESAMPLE    (ADSP_CONDITIONS_START + 5)
#define ADSP_MASTER_ACTIVE          (ADSP_CONDITIONS_START + 6)
#define ADSP_CONDITIONS_END         ADSP_MASTER_ACTIVE

#define ADSP_STRINGS_START          1350
#define ADSP_ACTIVE_STREAM_TYPE     (ADSP_STRINGS_START)
#define ADSP_DETECTED_STREAM_TYPE   (ADSP_STRINGS_START + 1)
#define ADSP_MASTER_NAME            (ADSP_STRINGS_START + 7)
#define ADSP_MASTER_INFO            (ADSP_STRINGS_START + 8)
#define ADSP_MASTER_OWN_ICON        (ADSP_STRINGS_START + 9)
#define ADSP_MASTER_OVERRIDE_ICON   (ADSP_STRINGS_START + 10)
#define ADSP_STRINGS_END            ADSP_MASTER_OVERRIDE_ICON
#define PVR_STRINGS_END             PVR_ACTUAL_STREAM_PROVIDER

#define WINDOW_PROPERTY             9993
#define WINDOW_IS_TOPMOST           9994
#define WINDOW_IS_VISIBLE           9995
#define WINDOW_NEXT                 9996
#define WINDOW_PREVIOUS             9997
#define WINDOW_IS_MEDIA             9998
#define WINDOW_IS_ACTIVE            9999

#define CONTROL_GET_LABEL           29996
#define CONTROL_IS_ENABLED          29997
#define CONTROL_IS_VISIBLE          29998
#define CONTROL_GROUP_HAS_FOCUS     29999
#define CONTROL_HAS_FOCUS           30000

<<<<<<< HEAD
#define LISTITEM_START                    35000
#define LISTITEM_THUMB                    (LISTITEM_START)
#define LISTITEM_LABEL                    (LISTITEM_START + 1)
#define LISTITEM_TITLE                    (LISTITEM_START + 2)
#define LISTITEM_TRACKNUMBER              (LISTITEM_START + 3)
#define LISTITEM_ARTIST                   (LISTITEM_START + 4)
#define LISTITEM_ALBUM                    (LISTITEM_START + 5)
#define LISTITEM_YEAR                     (LISTITEM_START + 6)
#define LISTITEM_GENRE                    (LISTITEM_START + 7)
#define LISTITEM_ICON                     (LISTITEM_START + 8)
#define LISTITEM_DIRECTOR                 (LISTITEM_START + 9)
#define LISTITEM_OVERLAY                  (LISTITEM_START + 10)
#define LISTITEM_LABEL2                   (LISTITEM_START + 11)
#define LISTITEM_FILENAME                 (LISTITEM_START + 12)
#define LISTITEM_DATE                     (LISTITEM_START + 13)
#define LISTITEM_SIZE                     (LISTITEM_START + 14)
#define LISTITEM_RATING                   (LISTITEM_START + 15)
#define LISTITEM_PROGRAM_COUNT            (LISTITEM_START + 16)
#define LISTITEM_DURATION                 (LISTITEM_START + 17)
#define LISTITEM_ISPLAYING                (LISTITEM_START + 18)
#define LISTITEM_ISSELECTED               (LISTITEM_START + 19)
#define LISTITEM_PLOT                     (LISTITEM_START + 20)
#define LISTITEM_PLOT_OUTLINE             (LISTITEM_START + 21)
#define LISTITEM_EPISODE                  (LISTITEM_START + 22)
#define LISTITEM_SEASON                   (LISTITEM_START + 23)
#define LISTITEM_TVSHOW                   (LISTITEM_START + 24)
#define LISTITEM_PREMIERED                (LISTITEM_START + 25)
#define LISTITEM_COMMENT                  (LISTITEM_START + 26)
#define LISTITEM_ACTUAL_ICON              (LISTITEM_START + 27)
#define LISTITEM_PATH                     (LISTITEM_START + 28)
#define LISTITEM_PICTURE_PATH             (LISTITEM_START + 29)
// the ordering of LISTITEM_PICTURE_* is important as they're mapped to SLIDE_* items in GUIInfoManager.cpp
#define LISTITEM_PICTURE_START            (LISTITEM_START + 30)
#define LISTITEM_PICTURE_RESOLUTION       (LISTITEM_PICTURE_START) // => SLIDE_RESOLUTION
#define LISTITEM_PICTURE_LONGDATE         (LISTITEM_START + 31)    // => SLIDE_EXIF_LONG_DATE
#define LISTITEM_PICTURE_LONGDATETIME     (LISTITEM_START + 32)    // => SLIDE_EXIF_LONG_DATE_TIME
#define LISTITEM_PICTURE_DATE             (LISTITEM_START + 33)    // => SLIDE_EXIF_DATE
#define LISTITEM_PICTURE_DATETIME         (LISTITEM_START + 34)    // => SLIDE_EXIF_DATE_TIME
#define LISTITEM_PICTURE_COMMENT          (LISTITEM_START + 35)    // => SLIDE_COMMENT
#define LISTITEM_PICTURE_CAPTION          (LISTITEM_START + 36)    // => SLIDE_IPTC_CAPTION
#define LISTITEM_PICTURE_DESC             (LISTITEM_START + 37)    // => SLIDE_EXIF_DESCRIPTION
#define LISTITEM_PICTURE_KEYWORDS         (LISTITEM_START + 38)    // => SLIDE_IPTC_KEYWORDS
#define LISTITEM_PICTURE_CAM_MAKE         (LISTITEM_START + 39)    // => SLIDE_EXIF_CAMERA_MAKE
#define LISTITEM_PICTURE_CAM_MODEL        (LISTITEM_START + 40)    // => SLIDE_EXIF_CAMERA_MODEL
#define LISTITEM_PICTURE_APERTURE         (LISTITEM_START + 41)    // => SLIDE_EXIF_APERTURE
#define LISTITEM_PICTURE_FOCAL_LEN        (LISTITEM_START + 42)    // => SLIDE_EXIF_FOCAL_LENGTH
#define LISTITEM_PICTURE_FOCUS_DIST       (LISTITEM_START + 43)    // => SLIDE_EXIF_FOCUS_DIST
#define LISTITEM_PICTURE_EXP_MODE         (LISTITEM_START + 44)    // => SLIDE_EXIF_EXPOSURE_MODE
#define LISTITEM_PICTURE_EXP_TIME         (LISTITEM_START + 45)    // => SLIDE_EXIF_EXPOSURE_TIME
#define LISTITEM_PICTURE_ISO              (LISTITEM_START + 46)    // => SLIDE_EXIF_ISO_EQUIV
#define LISTITEM_PICTURE_AUTHOR           (LISTITEM_START + 47) // => SLIDE_IPTC_AUTHOR
#define LISTITEM_PICTURE_BYLINE           (LISTITEM_START + 48) // => SLIDE_IPTC_BYLINE
#define LISTITEM_PICTURE_BYLINE_TITLE     (LISTITEM_START + 49) // => SLIDE_IPTC_BYLINE_TITLE
#define LISTITEM_PICTURE_CATEGORY         (LISTITEM_START + 50) // => SLIDE_IPTC_CATEGORY
#define LISTITEM_PICTURE_CCD_WIDTH        (LISTITEM_START + 51) // => SLIDE_EXIF_CCD_WIDTH
#define LISTITEM_PICTURE_CITY             (LISTITEM_START + 52) // => SLIDE_IPTC_CITY
#define LISTITEM_PICTURE_URGENCY          (LISTITEM_START + 53) // => SLIDE_IPTC_URGENCY
#define LISTITEM_PICTURE_COPYRIGHT_NOTICE (LISTITEM_START + 54) // => SLIDE_IPTC_COPYRIGHT_NOTICE
#define LISTITEM_PICTURE_COUNTRY          (LISTITEM_START + 55) // => SLIDE_IPTC_COUNTRY
#define LISTITEM_PICTURE_COUNTRY_CODE     (LISTITEM_START + 56) // => SLIDE_IPTC_COUNTRY_CODE
#define LISTITEM_PICTURE_CREDIT           (LISTITEM_START + 57) // => SLIDE_IPTC_CREDIT
#define LISTITEM_PICTURE_IPTCDATE         (LISTITEM_START + 58) // => SLIDE_IPTC_DATE
#define LISTITEM_PICTURE_DIGITAL_ZOOM     (LISTITEM_START + 59) // => SLIDE_EXIF_DIGITAL_ZOOM
#define LISTITEM_PICTURE_EXPOSURE         (LISTITEM_START + 60) // => SLIDE_EXIF_EXPOSURE
#define LISTITEM_PICTURE_EXPOSURE_BIAS    (LISTITEM_START + 61) // => SLIDE_EXIF_EXPOSURE_BIAS
#define LISTITEM_PICTURE_FLASH_USED       (LISTITEM_START + 62) // => SLIDE_EXIF_FLASH_USED
#define LISTITEM_PICTURE_HEADLINE         (LISTITEM_START + 63) // => SLIDE_IPTC_HEADLINE
#define LISTITEM_PICTURE_COLOUR           (LISTITEM_START + 64) // => SLIDE_COLOUR
#define LISTITEM_PICTURE_LIGHT_SOURCE     (LISTITEM_START + 65) // => SLIDE_EXIF_LIGHT_SOURCE
#define LISTITEM_PICTURE_METERING_MODE    (LISTITEM_START + 66) // => SLIDE_EXIF_METERING_MODE
#define LISTITEM_PICTURE_OBJECT_NAME      (LISTITEM_START + 67) // => SLIDE_IPTC_OBJECT_NAME
#define LISTITEM_PICTURE_ORIENTATION      (LISTITEM_START + 68) // => SLIDE_EXIF_ORIENTATION
#define LISTITEM_PICTURE_PROCESS          (LISTITEM_START + 69) // => SLIDE_PROCESS
#define LISTITEM_PICTURE_REF_SERVICE      (LISTITEM_START + 70) // => SLIDE_IPTC_REF_SERVICE
#define LISTITEM_PICTURE_SOURCE           (LISTITEM_START + 71) // => SLIDE_IPTC_SOURCE
#define LISTITEM_PICTURE_SPEC_INSTR       (LISTITEM_START + 72) // => SLIDE_IPTC_SPEC_INSTR
#define LISTITEM_PICTURE_STATE            (LISTITEM_START + 73) // => SLIDE_IPTC_STATE
#define LISTITEM_PICTURE_SUP_CATEGORIES   (LISTITEM_START + 74) // => SLIDE_IPTC_SUP_CATEGORIES
#define LISTITEM_PICTURE_TX_REFERENCE     (LISTITEM_START + 75) // => SLIDE_IPTC_TX_REFERENCE
#define LISTITEM_PICTURE_WHITE_BALANCE    (LISTITEM_START + 76) // => SLIDE_EXIF_WHITE_BALANCE
#define LISTITEM_PICTURE_IMAGETYPE        (LISTITEM_START + 77) // => SLIDE_IPTC_IMAGETYPE
#define LISTITEM_PICTURE_SUBLOCATION      (LISTITEM_START + 78) // => SLIDE_IPTC_SUBLOCATION
#define LISTITEM_PICTURE_TIMECREATED      (LISTITEM_START + 79) // => SLIDE_IPTC_TIMECREATED
#define LISTITEM_PICTURE_GPS_LAT    (LISTITEM_START + 80)    // => SLIDE_EXIF_GPS_LATITUDE
#define LISTITEM_PICTURE_GPS_LON    (LISTITEM_START + 81)    // => SLIDE_EXIF_GPS_LONGITUDE
#define LISTITEM_PICTURE_GPS_ALT    (LISTITEM_START + 82)    // => SLIDE_EXIF_GPS_ALTITUDE
#define LISTITEM_PICTURE_END        (LISTITEM_PICTURE_GPS_ALT)
#define LISTITEM_STUDIO             (LISTITEM_START + 83)
#define LISTITEM_MPAA               (LISTITEM_START + 84)
#define LISTITEM_CAST               (LISTITEM_START + 85)
#define LISTITEM_CAST_AND_ROLE      (LISTITEM_START + 86)
#define LISTITEM_WRITER             (LISTITEM_START + 87)
#define LISTITEM_TAGLINE            (LISTITEM_START + 88)
#define LISTITEM_TOP250             (LISTITEM_START + 89)
#define LISTITEM_RATING_AND_VOTES   (LISTITEM_START + 90)
#define LISTITEM_TRAILER            (LISTITEM_START + 91)
#define LISTITEM_STAR_RATING        (LISTITEM_START + 92)
#define LISTITEM_FILENAME_AND_PATH  (LISTITEM_START + 93)
#define LISTITEM_SORT_LETTER        (LISTITEM_START + 94)
#define LISTITEM_ALBUM_ARTIST       (LISTITEM_START + 95)
#define LISTITEM_FOLDERNAME         (LISTITEM_START + 96)
#define LISTITEM_VIDEO_CODEC        (LISTITEM_START + 97)
#define LISTITEM_VIDEO_RESOLUTION   (LISTITEM_START + 98)
#define LISTITEM_VIDEO_ASPECT       (LISTITEM_START + 99)
#define LISTITEM_AUDIO_CODEC        (LISTITEM_START + 100)
#define LISTITEM_AUDIO_CHANNELS     (LISTITEM_START + 101)
#define LISTITEM_AUDIO_LANGUAGE     (LISTITEM_START + 102)
#define LISTITEM_SUBTITLE_LANGUAGE  (LISTITEM_START + 103)
#define LISTITEM_IS_FOLDER          (LISTITEM_START + 104)
#define LISTITEM_ORIGINALTITLE      (LISTITEM_START + 105)
#define LISTITEM_COUNTRY            (LISTITEM_START + 106)
#define LISTITEM_PLAYCOUNT          (LISTITEM_START + 107)
#define LISTITEM_LASTPLAYED         (LISTITEM_START + 108)
#define LISTITEM_FOLDERPATH         (LISTITEM_START + 109)
#define LISTITEM_DISC_NUMBER        (LISTITEM_START + 110)
#define LISTITEM_FILE_EXTENSION     (LISTITEM_START + 111)
#define LISTITEM_IS_RESUMABLE       (LISTITEM_START + 112)
#define LISTITEM_PERCENT_PLAYED     (LISTITEM_START + 113)
#define LISTITEM_DATE_ADDED         (LISTITEM_START + 114)
#define LISTITEM_DBTYPE             (LISTITEM_START + 115)
#define LISTITEM_DBID               (LISTITEM_START + 116)

#define LISTITEM_STARTTIME          (LISTITEM_START + 117)
#define LISTITEM_ENDTIME            (LISTITEM_START + 118)
#define LISTITEM_STARTDATE          (LISTITEM_START + 119)
#define LISTITEM_ENDDATE            (LISTITEM_START + 120)
#define LISTITEM_NEXT_TITLE         (LISTITEM_START + 121)
#define LISTITEM_NEXT_GENRE         (LISTITEM_START + 122)
#define LISTITEM_NEXT_PLOT          (LISTITEM_START + 123)
#define LISTITEM_NEXT_PLOT_OUTLINE  (LISTITEM_START + 124)
#define LISTITEM_NEXT_STARTTIME     (LISTITEM_START + 125)
#define LISTITEM_NEXT_ENDTIME       (LISTITEM_START + 126)
#define LISTITEM_NEXT_STARTDATE     (LISTITEM_START + 127)
#define LISTITEM_NEXT_ENDDATE       (LISTITEM_START + 128)
#define LISTITEM_NEXT_DURATION      (LISTITEM_START + 129)
#define LISTITEM_CHANNEL_NAME       (LISTITEM_START + 130)
#define LISTITEM_CHANNEL_NUMBER     (LISTITEM_START + 131)
#define LISTITEM_CHANNEL_GROUP      (LISTITEM_START + 132)
#define LISTITEM_HASTIMER           (LISTITEM_START + 133)
#define LISTITEM_ISRECORDING        (LISTITEM_START + 134)
#define LISTITEM_ISENCRYPTED        (LISTITEM_START + 135)
#define LISTITEM_PARENTALRATING     (LISTITEM_START + 136)
#define LISTITEM_PROGRESS           (LISTITEM_START + 137)
#define LISTITEM_HAS_EPG            (LISTITEM_START + 138)
#define LISTITEM_VOTES              (LISTITEM_START + 139)
#define LISTITEM_STEREOSCOPIC_MODE  (LISTITEM_START + 140)
#define LISTITEM_IS_STEREOSCOPIC    (LISTITEM_START + 141)
#define LISTITEM_INPROGRESS         (LISTITEM_START + 142)
#define LISTITEM_HASRECORDING       (LISTITEM_START + 143)
#define LISTITEM_SUB_CHANNEL_NUMBER (LISTITEM_START + 144)
#define LISTITEM_CHANNEL_NUMBER_LBL (LISTITEM_START + 145)
#define LISTITEM_IMDBNUMBER         (LISTITEM_START + 146)
#define LISTITEM_EPISODENAME        (LISTITEM_START + 147)
#define LISTITEM_IS_COLLECTION      (LISTITEM_START + 148)

#define LISTITEM_PROPERTY_START     (LISTITEM_START + 200)
#define LISTITEM_PROPERTY_END       (LISTITEM_PROPERTY_START + 1000)
#define LISTITEM_END                (LISTITEM_PROPERTY_END)

#define MUSICPLAYER_PROPERTY_OFFSET 800 // 100 id's reserved for musicplayer props.
#define LISTITEM_ART_OFFSET         900 // 100 id's reserved for listitem art.

#define CONDITIONAL_LABEL_START       LISTITEM_END + 1 // 36001
#define CONDITIONAL_LABEL_END         37000

// the multiple information vector
#define MULTI_INFO_START              40000
#define MULTI_INFO_END                99999
#define COMBINED_VALUES_START        100000
// Info Flags
// Stored in the top 8 bits of GUIInfo::m_data1
// therefore we only have room for 8 flags
#define INFOFLAG_LISTITEM_WRAP        ((uint32_t) (1 << 25))  // Wrap ListItem lookups
#define INFOFLAG_LISTITEM_POSITION    ((uint32_t) (1 << 26))  // Absolute ListItem lookups